name: rektometer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 
  flutter_bloc: 
  dio: 
  google_fonts: 
  fl_chart: 
  syncfusion_flutter_gauges: 
  intl: 
  json_annotation: 
  freezed_annotation: 
  retrofit: 
  get_it: 
  injectable: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  json_serializable: 
  build_runner: 
  freezed: 
  retrofit_generator: 
  injectable_generator:


flutter:

  uses-material-design: true

  assets:
    - assets/images/

